### ISSUE TITLE
Path to old lombok.jar stays in settings.json after update

### ISSUE THREAD

**Issue by y0n3t4n1** [GabrielBB/vscode-lombok#3]
The path to lombok.jar is added to `java.jdt.ls.vmargs` the first time you use it, which is great, but when the extension is updated, the older path sits there and the newer path is not added.
With the older path remaining in `java.jdt.ls.vmargs`, the debug button or the cog button next to it stops working and there's no error messages displayed, leaving the user no clue on what to do to solve it.
I also found that out/uninstall.js looks like it tries to remove the `-javaagent:` part from `java.jdt.ls.vmargs` upon uninstall, but it's not changed after reloading or restarting the Code, although I'm not sure if uninstall.js is called on extension update.

**Comment by GabrielBB** [comment]
Hi, thanks for reporting this issue. Uninstall.js Is called by a VS Code event when uninstalling extensión but as you said, it seems it is not being called on extension update. If this is the case I will open an issue to the Visual Studio Code team because we developers need a way to clean up things on extension update too. Anyway, I will try to make a solution today

**Comment by GabrielBB** [comment]
Hi, i just fixed this issue: [Fixing issue #3](https://github.com/GabrielBB/vscode-lombok/commit/b72da528e4638b722aedd1ab5e0c31121a929128). Once again, thanks for reporting it. I'm closing this issue now
