### ISSUE TITLE
Cannot install lombok extension behind corporate proxy.

### ISSUE THREAD

**Issue by Skronner** [GabrielBB/vscode-lombok#34]
Error messages: 
1) "Failed to install 'gabrielbb.vscode-lombok'" on install from VS Code.
2) "EPERM: operation not permitted, mkdir 'C:\Users\f1694870\\.vscode\extensions\\.gabrielbb.vscode-lombok-1.0.1\node_modules\uc.micro' when installing from downloaded file.

Lombok was already installed for Eclipse and is working.
Im using  JDK 8 and JRE 1.8.

**Comment by GabrielBB** [comment]
Looks like your Windows is denying it. Try to open VSCode as Administrator and install it again

**Comment by Skronner** [comment]
Im sorry, but i´ve already done it before posting the issue. Running VS Code as Administrator doesn´t change the results, throwing the same error messages for both cases.

**Comment by mithunkavullakandiyil** [comment]
@Skronner Is McAfee your anti-virus software? I believe this is to do with antivirus software not allowing to create the uc.micro folder. I am also facing the same issue.

**Comment by GabrielBB** [comment]
@mithunkavullakandiyil When you turned the anti virus off , did it work ?

**Comment by mithunkavullakandiyil** [comment]
> @mithunkavullakandiyil When you turned the anti virus off , did it work ?

@GabrielBB Unfortunately in my office laptop, I do not have the permission to turn off the Anti Virus. But I have found similar threads/issues of McAfee preventing to create uc.micro installations. 

You can refer VS Code installation issue caused before due to the same issue below.
[VS Code Setup Error - uc.micro folder creation access is denied by Antivirus #13559](https://github.com/Microsoft/vscode/issues/13559)

**Comment by GabrielBB** [comment]
Great @mithunkavullakandiyil . Thanks for informing this. I will be closing this issue then since it is an issue with McAfee
