### ISSUE TITLE
No extension found (VSCodium)

### ISSUE THREAD

**Issue by lrkwz** [GabrielBB/vscode-lombok#41]
I'm using the latest VSCodium and I have a "No extension found" message. Even `ext install GabrielBB.vscode-lombok` fails silently.

![image](https://user-images.githubusercontent.com/1025560/85700597-d3c22d80-b6dc-11ea-8f4d-448aa8d30d72.png)

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T10:53:55.306Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic
```

**Comment by ivan-levelops** [comment]
The issue is that vscodium and vscode use by default different extension repositories (Galleries).

You can follow the comment in  [here](https://github.com/VSCodium/vscodium/issues/72) to change the extensions gallery used by vscodium.

**File: <path to codium>/resources/app/product.json**

**New extensionsGallery contents:**
>     
       "extensionsGallery": {
         "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
         "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
         "itemUrl": "https://marketplace.visualstudio.com/items",
         "controlUrl": "https://az764295.vo.msecnd.net/extensions/marketplace.json",
         "recommendationsUrl": "https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz"
       }

You should be good by simply changing the `serviceUrl` and the `itemUrl`.


Additionally, I published the lombok extension in the open-vsx repo but you may run into other dependencies issues.

**Comment by cool2k** [comment]
The issue is that vscodium and vscode use by default different extension repositories (Galleries).

You can follow the comment in  [here](https://github.com/VSCodium/vscodium/issues/72) to change the extensions gallery used by vscodium.

**File: <path to codium>/resources/app/product.json**

**New extensionsGallery contents:**
>     
       "extensionsGallery": {
         "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
         "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
         "itemUrl": "https://marketplace.visualstudio.com/items",
         "controlUrl": "https://az764295.vo.msecnd.net/extensions/marketplace.json",
         "recommendationsUrl": "https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz"
       }

You should be good by simply changing the `serviceUrl` and the `itemUrl`.


Additionally, I published the `lombok` extension in the `open-vsx` repo but you may run into other dependencies issues.

**Comment by GabrielBB** [comment]
Thanks for pushing the extension there
